### ISSUE TITLE
QQ浏览器下全屏鼠标无隐藏

### ISSUE THREAD

**Issue by tnti** [gooyie/ykh5p#2]
全屏鼠标没隐藏 播放控件几秒隐藏一下又出来 这样一直在往复 装在QQ浏览器+tampermonkey 不知道咋回事 过来问问大佬..

**Comment by gooyie** [comment]
我去装了QQ浏览器9测试，不会出现你说的情况，全屏鼠标隐藏正常。

**Comment by tnti** [comment]
回头我换个浏览器看看 关了所有插件也还是全屏下就是1S隐藏了 然后又2S显示那些播放控件
不全屏下鼠标不放在播放窗口就没事
