### ISSUE TITLE
cent browser 状态栏显示 正在等待ykatr.youku.com的响应...

### ISSUE THREAD

**Issue by 527570755** [gooyie/ykh5p#5]
win 10 专业版64位  Cent Browser 版本 2.7.4.52（正式版本） （32 位） (Chromium 59.0.3071.115)
看优酷的时候，左下角状态栏显示 正在等待ykatr.youku.com的响应...，约1分半后才会自动消失，之前用flash没有这种问题，后来用h5发现这个问题后，再改回flash，也这样了。主要全屏左下角一直显示 太难受
可能是个人电脑原因，和hosts，其他插件无关。

![qq 20170815234034](https://user-images.githubusercontent.com/31041923/29340197-5e4423ec-8250-11e7-9807-316080ee868d.png)

**Comment by gooyie** [comment]
![2017-08-16_120002](https://user-images.githubusercontent.com/25021141/29347423-26d77146-827f-11e7-8e9d-efc226070bd8.png)

502了，应该是优酷的问题吧。
加个规则拦截掉就不用等超时了。
```
||ykatr.youku.com/atr/related/packed_list.json$script
```

**Comment by 527570755** [comment]
已解决，开心到飞起，真是一种享受
