### ISSUE TITLE
关闭后 优酷依然html5播放

### ISSUE THREAD

**Issue by fooxxkgod** [gooyie/ykh5p#6]
![default](https://user-images.githubusercontent.com/20237870/29486788-cf2705b6-8520-11e7-9abd-bcc6cce15184.PNG)

**Comment by fooxxkgod** [comment]
删除脚本和油猴也依然html5播放 左面也有切换按钮

**Comment by gooyie** [comment]
在控制台执行`sessionStorage.getItem('P_l_h5')`，给出结果。

**Comment by fooxxkgod** [comment]
![default](https://user-images.githubusercontent.com/20237870/29548445-85442c66-8733-11e7-9416-cc020df2c7d4.PNG)
仍然无效

**Comment by fooxxkgod** [comment]
多谢帮助 发现是屏蔽视频广告的软件记录了将youku转为html5的默认设置   将其重装就好了
麻烦你了

**Comment by lirener** [comment]
我也遇到了这个问题……关闭脚本有锁住html5现象
而且原先1080P处变成了自动 然后能看到右上角出现优酷独播和youku的软水印 记得原来好像没有……
![5665](https://user-images.githubusercontent.com/19354130/29715383-c75b8a24-89d9-11e7-9d23-66d2a4ba8386.png)
![233](https://user-images.githubusercontent.com/19354130/29715482-1ddba37a-89da-11e7-8f9d-d9f805951727.png)
![343](https://user-images.githubusercontent.com/19354130/29715484-1e5687ac-89da-11e7-8e4c-c65866fecdde.png)
![2315](https://user-images.githubusercontent.com/19354130/29715485-1e8d087c-89da-11e7-8b71-bf2a0fd2573f.png)

**Comment by lirener** [comment]
现在主要表现为2个问题 就是点视频无法暂停 还有可能出现的右上角双水印……
![44444](https://user-images.githubusercontent.com/19354130/29715827-80f91a40-89db-11e7-93e4-c99bb62482ce.png)
![5656](https://user-images.githubusercontent.com/19354130/29715828-812c4154-89db-11e7-8701-82ef598e87e0.png)
而且我不知道是从啥版本开始不能右击查看视频信息 以前早期html5好像可以 现在只能flash查看
正常网页右击视频没反应 和点外围空白网页的右击提示一样 不能像youtube那样查看信息测网速...

**Comment by gooyie** [comment]
右击可以查看视频信息应该是flash播放器吧

**Comment by lirener** [comment]
是啊 以前html5有一段时间记得也可以的

**Comment by GoogleGFW** [comment]
右键查看视频信息那是扩展版H5的功能，官方版H5没有。

**Comment by gooyie** [comment]
@lirener  你应该不会分不清是扩展h5还是官方h5吧
