### ISSUE TITLE
老哥，渣酷HTML5播放器更新了

### ISSUE THREAD

**Issue by GoogleGFW** [gooyie/ykh5p#7]
快捷键失效了，1080每次都点一下还可以使用。

现在点开视频也不自动播放，还得点下播放键，

而且那个“播放下一集”的按钮还是个摆设，点了跳回起点暂停播放，擦了。。渣酷更新的什么鬼。。
![qq 20170825211021](https://user-images.githubusercontent.com/26985927/29715405-db7b53a4-89d9-11e7-8030-cbf048a97f19.png)

**Comment by lirener** [comment]
...是的 我很少看优酷也是才发现 主要是暂停也不方便了

**Comment by Cowan97** [comment]
空格暂停也出问题了= =。按了空格后，暂停是暂停了，网页也下滑了。。。是忘了屏蔽空格向下翻页么。。

**Comment by gooyie** [comment]
渣酷的h5播放器已经消失了。

**Comment by gooyie** [comment]
渣酷不让用了
```js
            var v = "h5" === l.debug || (d ? d.getItem("P_l_h5") : "");
            if (!f && p && (m || v) && false) {
                window.ykPlyr = new t({
                    el: "#player"
                });
                ykPlyr.one("loadedH5:sucess", function(e) {
                    s.h5Bind(e, ykPlyr);
                    window.H5player = e
                });
                $("#module_basic_playarea").addClass("spv-player");
                d && d.setItem("P_l_h5", true)
            } else {
                window.ykPlyr = new e;
                s.swfBind(ykPlyr);
                new o({});
                d && d.removeItem("P_l_h5")
            }
```

**Comment by lirener** [comment]
那真是令人叹息的操作..........现在大不如前了！

**Comment by GoogleGFW** [comment]
那没办法只能用扩展版了，
脚本的用起来比较舒服，各种快捷键操作方便，唉。。。

**Comment by gooyie** [comment]
原先的播放器代码可能被当成实验品仍了，这个是重造的……
脚本现在可以用了，不过毕竟还是渣酷的实验品。虽然实现了略缩图预览、音量记忆，但还是问题多多。

**Comment by GoogleGFW** [comment]
晚上的版本比较中午的版本恢复了更多的功能，
除了视频不自动播放，切换上下集无效之外，别的基本都正常了。
之前一直以为点击”下一集“按钮是跳回本集视频起点并暂停，
刚才比较视频内容才发现，原来是跳转到下一集了但是标题不变，等待手动点击播放，我勒个擦。。
老哥辛苦了！

**Comment by gooyie** [comment]
现在的播放器有两种实现，第一种用的是hls.js单video元素，第二种类似腾讯的h5播放器用多个video元素来实现播放分段mp4。两种实现在功能上有差异，渣酷还在测试这两种实现，所以才会出现不同时间功能上有所差异。
之前好像会自动播放的，现在不自动播放了。”下一集“按钮有bug，点击后控制台会出现未捕获异常。脚本的上下集快捷键还没实现。

**Comment by lirener** [comment]
辛苦辛苦 厉害了老哥 暂停恢复了~也不会全屏卡播放器进度条了 也可以支持https播放了~稳~那些热键和下一集我一般很少用 就看看1080P的番剧更新~可以了 加油 继续努力 我支持你
