### ISSUE TITLE
画质选择问题

### ISSUE THREAD

**Issue by Cowan97** [gooyie/ykh5p#8]
发现一个问题。
在选择优先画质后，打开视频。虽然标注的是选择优先画质的那个选项，但实际上是标清的画质，望尽快修复。

**Comment by Cowan97** [comment]
发现第二个问题，按键盘左键倒退，怎么成快进了。不科学啊

**Comment by gooyie** [comment]
我用`ffpobe`查看了播放的视频，不会出选择的画质与实际不符这种情况。你看的哪个视频？
左键倒退？不会吧？应该其它脚本或扩展冲突了吧？
