### ISSUE TITLE
卡在加载界面不能播放，控制台报错

### ISSUE THREAD

**Issue by kuaitou286** [gooyie/ykh5p#9]
![tim 20170905192922](https://user-images.githubusercontent.com/10684972/30059157-8d95bc20-9270-11e7-8895-b0e5b90d3e1f.png)

![tim 20170905192508](https://user-images.githubusercontent.com/10684972/30059053-147454aa-9270-11e7-9d3e-330a4cee20bf.png)

![tim 20170905192540](https://user-images.githubusercontent.com/10684972/30059054-153999d6-9270-11e7-9878-9f61d3517315.png)

**Comment by gooyie** [comment]
哪个视频，给个链接。

**Comment by kuaitou286** [comment]
http://v.youku.com/v_show/id_XMjk4OTAxNTQyMA==.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.1
随便一个视频都这样 现在公司的电脑上出了新的问题，应该差不多
那个上面的错误是家里电脑上     长城宽带 
下面的错误是在公司电脑上         貌似是 联通

![tim 20170906081602](https://user-images.githubusercontent.com/10684972/30088934-fff655ac-92db-11e7-9c61-493c8ca8714c.png)

![tim 20170906081614](https://user-images.githubusercontent.com/10684972/30088933-fff5707e-92db-11e7-9ff8-984f97b8aaee.png)
